server:
  port: 3001
spring:
  application:
     name: user-consumer #不要使用下划线
eureka:
  client:
    service-url:
      defaultZone:  http://eureka-1001.com:1001/eureka/,http://eureka-1000.com:1000/eureka/ #告诉服务提供者要把服务注册到哪儿
  instance:
    prefer-ip-address: true #显示客户端真实ip